### ISSUE TITLE
non-destructive installation only applies to ventoy windows version

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#1221] opened 2021-11-11 19:58 UTC
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.59

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GP

### Disk Manufacturer

TOSHIBA

### Image file checksum (if applicable)

No.

### What happened?

A bug happened!Does the non-destructive installation only apply to the Windows version of Ventoy?

**Comment by ventoy** [comment] 2021-11-12 00:58
Duplicate of #1219

**Closed** 2021-11-12 03:55 UTC

**Comment by ventoy** [comment] 2021-11-12 12:13
Ventoy 1.0.60
Add non-destructive installation support in Linux Ventoy2Disk.sh. [Notes](https://www.ventoy.net/en/doc_non_destructive.html)
