### ISSUE TITLE
ventoy on iso

### ISSUE THREAD

**Issue by nguyenhathaitrong** [ventoy/Ventoy#902] opened 2021-05-13 10:43 UTC
https://user-images.githubusercontent.com/71330863/118115027-978ddd80-b412-11eb-9f55-6cd6ccfc4dc7.mp4

**Comment by ventoy** [comment] 2021-05-13 11:23
Duplicate of #772

**Closed by ventoy** 2021-05-13 11:23 UTC

**Comment by nguyenhathaitrong** [comment] 2021-05-13 15:24
ven43.vhd
<https://drive.google.com/file/d/1PnMeyFRRmyxvcP5VkEkGk_uQ9kEPp2Z-/view?usp=drive_web>
