### ISSUE TITLE
fedyos img launch fail

### ISSUE THREAD

**Issue by sonichy** [ventoy/Ventoy#994] opened 2021-07-09 02:55 UTC
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.46

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### What happened?

A bug happened!

**Comment by ventoy** [comment] 2021-07-09 07:34
fedyos is based on chromeos which is not supported now.

**Comment by ventoy** [comment] 2021-07-09 09:40
Duplicate of #760

**Closed** 2021-07-09 15:43 UTC
