### ISSUE TITLE
How to set to get that Ventoy always boots successfully whether secure boot is enabled or disabled.

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1420] opened 2022-02-03 12:30 UTC
How can I set to get that Ventoy always boots successfully whether secure boot is enabled or disabled.

If "secure boot [√]”  when setting Ventoy before installing, it cannot boot because BIOS has been set that secure boot is disabled, and Ventoy booting needs secure boot enabled.

If "secure boot [ ]”  when setting Ventoy before installing, it cannot boot because BIOS has been set that secure boot is enabled, and Ventoy booting needs secure boot disabled.

**Comment by ventoy** [comment] 2022-02-03 13:46
Duplicate of #1414

**Closed by ventoy** 2022-02-03 13:46 UTC
