### ISSUE TITLE
ESET SysRescue boot failure: 

### ISSUE THREAD

**Issue by estevaog3** [ventoy/Ventoy#44] opened 2020-05-02 17:08 UTC
The ISO `eset_sysrescue_live_enu` didn't booted on two different 64 bits legacy (BIOS) machines of mine. 
1. The following error occurred on the first computer.
![ventoy-eset](https://user-images.githubusercontent.com/22309462/80870645-cc028180-8c75-11ea-9762-987bc41556a2.jpg)

2. A similar screen appeared on the second machine (sorry for the low image quality on this one):
![photo5004038196270573617](https://user-images.githubusercontent.com/22309462/80870625-a37a8780-8c75-11ea-8f86-d06d865634b6.jpg)

**Comment by chromer030** [comment] 2020-05-02 17:36
ESET SysRescue boots fine on UEFI but has some issues on BIOS mode.

**Comment by EstevaoCostaG3** [comment] 2020-05-02 18:51
But according to the [tested list](https://www.ventoy.net/en/isolist.html), ESET SysRescue works on both UEFI and BIOS mode. So they should update this status, since it doesn't work in legacy mode.

**Comment by ventoy** [comment] 2020-05-03 00:03
Please just cat /ventoy/log and send me the log, thanks!

**Comment by soares23** [comment] 2020-05-03 01:00
Hi, have same problem in **Uefi** and **Legacy** Boot. Version of Ventoy 1.0.08.

![error-eset](https://user-images.githubusercontent.com/560476/80896024-263d2a00-8cea-11ea-9f0f-b5393cecf97d.jpg)

**Comment by ventoy** [comment] 2020-05-03 03:50
Hi,
I also reproduced this problem on my own machine, so I made a mistake in the tested iso list, I have updated it.
This is a relatively simple question, I have fixed it up. So it will be OK in the next release. I will update the list again after the next release.

**Comment by soares23** [comment] 2020-05-03 13:49
ok thank's it was only to tell you does it's not working, that the project can grou up with compatiblity.

**Comment by EstevaoCostaG3** [comment] 2020-05-03 17:29
@ventoy Great! So it seems that I don't need to show my Ventoy log file anymore. Therefore, on next release I will test it, and if it indeed works, I'll close this issue.

**Comment by ventoy** [comment] 2020-05-04 16:12
You can try ventoy-1.0.09 beta1

**Comment by ventoy** [comment] 2020-05-11 04:13
Is it ok with Ventoy-1.0.09 ?

**Comment by EstevaoCostaG3** [comment] 2020-05-12 19:05
> Is it ok with Ventoy-1.0.09 ?

I'm now getting a black screen with a single blinking underscore in it. I've tested on the second machine mentioned previously on this issue, I don't have access to the first one any more.

**Comment by ventoy** [comment] 2021-10-18 02:31
This is an old issue. If you still have problem with latest release, you can reopen the issue.

**Closed by ventoy** 2021-10-18 02:31 UTC
