### ISSUE TITLE
ventoy not working in Linux Mint

### ISSUE THREAD

**Issue by gauravnumber** [ventoy/Ventoy#695] opened 2021-01-12 15:02 UTC
I run this command.
```
sudo sh Ventoy2Disk.sh -i /dev/sdb
```

Output is 
```
**********************************************
      Ventoy: 1.0.31  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Disk : /dev/sdb
Model: Generic Flash Disk (scsi)
Size : 7 GB
Style: MBR


Attention:
You will install Ventoy to /dev/sdb.
All the data on the disk /dev/sdb will be lost!!!

Continue? (y/n) y

All the data on the disk /dev/sdb will be lost!!!
Double-check. Continue? (y/n) y

Create partitions on /dev/sdb by parted in MBR style ...
Done
mkfs on disk partitions ...
create efi fat fs /dev/sdb2 ...
mkfs.fat 4.1 (2017-01-24)
success
mkexfatfs 1.3.0
Creating... done.
Flushing... done.
File system created successfully.
writing data to disk ...
sync data ...
esp partition processing ...
mount: /home/gaurav/Downloads/ventoy-1.0.31/tmp_mnt: wrong fs type, bad option, bad superblock on /dev/sdb2, missing codepage or helper program, or other error.
mount: /home/gaurav/Downloads/ventoy-1.0.31/tmp_mnt: wrong fs type, bad option, bad superblock on /dev/sdb2, missing codepage or helper program, or other error.
mount: /home/gaurav/Downloads/ventoy-1.0.31/tmp_mnt: wrong fs type, bad option, bad superblock on /dev/sdb2, missing codepage or helper program, or other error.
mv: cannot stat './tmp_mnt/EFI/BOOT/grubx64_real.efi': No such file or directory
mv: cannot stat './tmp_mnt/EFI/BOOT/grubia32_real.efi': No such file or directory
umount: ./tmp_mnt: not mounted.
umount: ./tmp_mnt: not mounted.
umount: ./tmp_mnt: not mounted.

Install Ventoy to /dev/sdb successfully finished.
```

If I put ISO file in my flash drive. I got GRUB error when I try to boot up.

**Comment by ventoy** [comment] 2021-01-13 01:16
Please refer #689  and check whether your USB stick has some hardware problem.

**Comment by ventoy** [comment] 2021-01-13 01:31
PS:
I have recieved many reports which finally turned out to be a USB hardware problem.
Most of them have a name `Generic Flash Disk`
In normal case, the name should be `Sandisk` `Kingston` ......

**Comment by git70** [comment] 2021-01-15 13:44
I can confirm - I had the same problem a few days ago (also Mint, but it's not a Mint problem)
Changing the USB stick to SanDisk solved the problem.

**Comment by gauravnumber** [comment] 2021-01-15 17:10
Sorry for the late reply.

I follow [those](https://github.com/ventoy/Ventoy/issues/689#issuecomment-756493926) steps.
I got error in step 3
```
sudo dd if=ventoy.disk.img of=/dev/sdc conv=fsync bs=512 count=65536 seek=65470464
```

Output
```
dd: /dev/sdb: cannot seek: Invalid argument
0+0 records in
0+0 records out
0 bytes copied, 0.000156252 s, 0.0 kB/s
```
Disks Screenshort
![Screenshot from 2021-01-15 22-33-16](https://user-images.githubusercontent.com/75254747/104756382-bee4de80-5781-11eb-89da-9c39b9c85693.png)

I tried [Balena Etcher](https://www.balena.io/etcher/) for use [Alpine Linux](https://www.alpinelinux.org/) and it's works. I not understand why ventoy not working. If any problem with flash drive it may also not working in Alpine Linux but it works.

**Comment by gauravnumber** [comment] 2021-01-15 17:11
> I can confirm - I had the same problem a few days ago (also Mint, but it's not a Mint problem)
> Changing the USB stick to SanDisk solved the problem.

I have a SanDisk flash drive.
I am also using Linux Mint

**Comment by ventoy** [comment] 2021-01-16 02:28
@gauravnumber 
`seek=65470464` the parameter 65470464 is depended on the hardware USB capacity. In #689 his USB stick is 32GB, but yours is 8GB, so you can't use 65470464.  You should use  `16318464`  in step3 and step4.

I think the problem is when I write data to the end of the USB stick. 
There is a big difference between Ventoy and other tools(e.g. Etcher).  When use Ventoy, it will write data to the beginning of the USB stick and also write some data to the end of the USB stick.  When you use Etcher, it write all the data from the beginning of the USB stick, so if the ISO file is 1GB, it will only write data to the first 1GB space of the USB stick.

Here is Ventoy's disk layout. https://www.ventoy.net/en/doc_disk_layout.html

**Comment by ventoy** [comment] 2021-01-16 02:31
> > I can confirm - I had the same problem a few days ago (also Mint, but it's not a Mint problem)
> > Changing the USB stick to SanDisk solved the problem.
> 
> I have a SanDisk flash drive.
> I am also using Linux Mint

Does your SanDisk flash drive have the same problem?

**Comment by gauravnumber** [comment] 2021-01-16 05:55
May be my pen drive have some bad sector.
In [step 4](https://github.com/ventoy/Ventoy/issues/689#issuecomment-756493926) `md5sum dump.img` will generate different result.
```
md5sum dump.img   
55e9f5824a39e3792876ac88d0e1da26  dump.img
```

Thanks for helping me.

**Comment by ventoy** [comment] 2021-01-16 06:34
OK. I will close the issue now.

**Closed by ventoy** 2021-01-16 06:34 UTC
